import ftplib, json, sys
cfg=json.load(open('.vscode/sftp.json'))
ftp=ftplib.FTP()
ftp.connect(cfg['host'], int(cfg.get('port',21)))
ftp.login(cfg['username'], cfg['password'])
ftp.set_pasv(cfg.get('passive',True))
ftp.cwd('/httpdocs/liturgia')
print('CWD:', ftp.pwd())
print('LIST:')
print('\n'.join(ftp.nlst()))
print('\n---FILE START---')
ftp.retrbinary('RETR index.php', sys.stdout.buffer.write)
print('\n---FILE END---')
ftp.quit()
